/**
 * About Me & Skills
 */
export const about = {
  aboutMe:
    "Backend/platform engineer with experience architecting and scaling operationally critical systems across IoT, fintech, and multi-tenant SaaS platforms.\n\nMy recent work includes building telemetry ingestion pipelines processing over 14 million daily events from 5,000+ lithium-ion batteries, implementing CAN telemetry decoding and Teltonika Codec8/Codec12 parsers, and architecting payment infrastructure handling $10M+ in monthly transaction volume.\n\nI specialize in distributed systems, event-driven architectures, operational tooling, and high-scale backend infrastructure. My stack primarily revolves around TypeScript/Node.js (NestJS, Fastify, Hono), PostgreSQL, RabbitMQ, AWS, and React, with recent work exploring agentic AI systems using LangGraph, FastAPI, vector databases, and local-first retrieval pipelines.",
  skills: [
    "Python",
    "JavaScript",
    "TypeScript",
    "Go",
    "C++",
    "Rust",
    "Java",
    "FastAPI",
    "React",
    "Node.js",
    "Express",
    "NestJS",
    "Fastify",
    "Hono",
    "Next.js",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "SQLite",
    "RabbitMQ",
    "Redis",
    "AWS",
    "Docker",
    "CI/CD",
    "WebSockets",
    "TanStack Query",
    "LangGraph",
    "LangChain",
    "FAISS",
    "ChromaDB",
    "Ollama",
    "Tavily",
    "Serper",
    "CAN Bus",
    "Teltonika Codec8/Codec12",
    "IoT Telemetry",
    "Distributed Systems",
  ],
};
